# Generated by Django 6.1.1 on 2026-09-22 04:48

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('hero_eyebrow', models.CharField(max_length=255, verbose_name='Надпись над главным заголовком')),
                ('hero_title_line', models.CharField(max_length=255, verbose_name='Главный заголовок — первая строка')),
                ('hero_title_accent', models.CharField(max_length=255, verbose_name='Главный заголовок — цветная строка')),
                ('hero_lead', models.TextField(verbose_name='Описание под главным заголовком')),
                ('hero_primary_label', models.CharField(max_length=100, verbose_name='Текст основной кнопки')),
                ('hero_primary_link', models.CharField(default='#contact', max_length=255, verbose_name='Ссылка основной кнопки')),
                ('hero_secondary_label', models.CharField(max_length=100, verbose_name='Текст дополнительной ссылки')),
                ('hero_secondary_link', models.CharField(default='#services', max_length=255, verbose_name='Ссылка дополнительной ссылки')),
                ('hero_line_number', models.CharField(default='01', max_length=12, verbose_name='Номер в строке под первым экраном')),
                ('hero_line_left', models.CharField(max_length=255, verbose_name='Левая часть строки под первым экраном')),
                ('hero_line_right', models.CharField(max_length=255, verbose_name='Правая часть строки под первым экраном')),
                ('core_label', models.CharField(default='IT', max_length=32, verbose_name='Текст в центре схемы')),
                ('core_subtitle', models.CharField(default='под ключ', max_length=100, verbose_name='Подпись в центре схемы')),
                ('visual_caption_line_one', models.CharField(max_length=100, verbose_name='Подпись схемы — строка 1')),
                ('visual_caption_line_two', models.CharField(max_length=100, verbose_name='Подпись схемы — строка 2')),
                ('overview_eyebrow', models.CharField(max_length=255, verbose_name='IT-сопровождение — надпись')),
                ('overview_title_line', models.CharField(max_length=255, verbose_name='IT-сопровождение — первая строка')),
                ('overview_title_accent', models.CharField(max_length=255, verbose_name='IT-сопровождение — цветная строка')),
                ('overview_body', models.TextField(verbose_name='IT-сопровождение — описание')),
                ('services_eyebrow', models.CharField(max_length=255, verbose_name='Услуги — надпись')),
                ('services_title_line', models.CharField(max_length=255, verbose_name='Услуги — первая строка')),
                ('services_title_accent', models.CharField(max_length=255, verbose_name='Услуги — цветная строка')),
                ('services_body', models.TextField(verbose_name='Услуги — описание')),
                ('result_eyebrow', models.CharField(max_length=255, verbose_name='Результат — надпись')),
                ('result_title_line', models.CharField(max_length=255, verbose_name='Результат — первая строка')),
                ('result_title_accent', models.CharField(max_length=255, verbose_name='Результат — цветная строка')),
                ('result_intro', models.TextField(verbose_name='Результат — главное описание')),
                ('partners_eyebrow', models.CharField(max_length=255, verbose_name='Партнёры — надпись')),
                ('partners_body', models.TextField(verbose_name='Партнёры — описание')),
                ('certificates_eyebrow', models.CharField(max_length=255, verbose_name='Сертификаты — надпись')),
                ('certificates_title_line', models.CharField(max_length=255, verbose_name='Сертификаты — первая строка')),
                ('certificates_title_accent', models.CharField(max_length=255, verbose_name='Сертификаты — цветная строка')),
                ('certificates_body', models.TextField(verbose_name='Сертификаты — описание')),
                ('contact_eyebrow', models.CharField(max_length=255, verbose_name='Контакты — надпись')),
                ('contact_title_line', models.CharField(max_length=255, verbose_name='Контакты — первая строка')),
                ('contact_title_accent', models.CharField(max_length=255, verbose_name='Контакты — цветная строка')),
                ('contact_button_label', models.CharField(max_length=100, verbose_name='Контакты — текст кнопки')),
                ('contact_button_link', models.CharField(default='#top', max_length=255, verbose_name='Контакты — ссылка кнопки')),
                ('contact_note', models.TextField(verbose_name='Контакты — пояснение')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HeroSystemNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.TextField(help_text='Перенос строки можно сделать клавишей Enter.', max_length=100, verbose_name='Текст узла')),
                ('position', models.CharField(choices=[('top', 'Сверху'), ('right', 'Справа'), ('bottom', 'Снизу'), ('left', 'Слева'), ('mobile', 'Сверху справа (Mobile Apps)')], max_length=20, verbose_name='Расположение')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_nodes', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('issuer', models.CharField(blank=True, max_length=255, verbose_name='Кем выдан / подпись')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='Статус или дополнительная подпись')),
                ('external_link', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('show_on_site', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Файл для скачивания')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Превью документа')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ITFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Описание')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_features', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100, verbose_name='Текст пункта меню')),
                ('anchor', models.CharField(help_text='Например: #services', max_length=255, verbose_name='Ссылка или якорь')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название партнёра')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Описание логотипа')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=500, verbose_name='Текст пункта')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_benefits', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(max_length=12, verbose_name='Номер')),
                ('icon', models.CharField(default='⌘', max_length=16, verbose_name='Символ иконки')),
                ('title_line_one', models.CharField(max_length=100, verbose_name='Заголовок — строка 1')),
                ('title_line_two', models.CharField(blank=True, max_length=100, verbose_name='Заголовок — строка 2')),
                ('body', models.TextField(verbose_name='Описание')),
                ('cta_label', models.CharField(default='Подробнее', max_length=100, verbose_name='Текст ссылки')),
                ('cta_link', models.CharField(default='#contact', max_length=255, verbose_name='Ссылка')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Выделить карточку')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_alt', models.CharField(default='Best Service', max_length=255, verbose_name='Описание логотипа')),
                ('header_cta_label', models.CharField(default='Обсудить задачу', max_length=100, verbose_name='Текст кнопки в шапке')),
                ('header_cta_link', models.CharField(default='#contact', max_length=255, verbose_name='Ссылка кнопки в шапке')),
                ('footer_tagline', models.CharField(default='IT под ключ для бизнеса', max_length=255, verbose_name='Текст в подвале')),
                ('copyright_text', models.CharField(default='© 2026 Best Service', max_length=255, verbose_name='Копирайт')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки Best Service',
            },
        ),
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100, verbose_name='Текст')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_items', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
