# Generated by Django 6.1.1 on 2026-09-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='certificates_aria_label',
            field=models.CharField(default='Галерея сертификатов', max_length=255, verbose_name='Описание галереи сертификатов для экранных читалок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_visual_aria_label',
            field=models.CharField(default='Схема единой IT-системы', max_length=255, verbose_name='Описание схемы для экранных читалок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='navigation_aria_label',
            field=models.CharField(default='Главное меню', max_length=255, verbose_name='Описание главного меню для экранных читалок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ticker_aria_label',
            field=models.CharField(default='Направления работы', max_length=255, verbose_name='Описание бегущей строки для экранных читалок'),
        ),
    ]
