# Generated by Django 6.1.1 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homepage_certificates_aria_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="is_landscape",
            field=models.BooleanField(
                default=False,
                help_text="Включите для горизонтального сертификата: он появится отдельной строкой из двух карточек.",
                verbose_name="Горизонтальный формат",
            ),
        ),
    ]
